In [1]:
import pandas as pd

In [2]:
path_1 = "./data/mexico-real-estate-1.csv"
df1 = pd.read_csv(path_1)
df1

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.0,"$94,835.67"
...,...,...,...,...,...,...
695,house,Morelos,NaN,NaN,310.0,"$237,089.17"
696,house,Yucatán,21.050653,-89.558841,334.0,"$137,017.34"
697,house,Yucatán,21.343796,-89.262060,130.0,"$110,404.35"
698,apartment,Nuevo León,NaN,NaN,155.0,"$184,446.42"
699,house,Querétaro,20.587378,-100.418361,106.0,"$56,637.97"

In [3]:
df1.head()

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.0,"$94,835.67"

In [4]:
df1.shape

(700, 6)

In [5]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  700 non-null    str
 1   state          700 non-null    str
 2   lat            583 non-null    float64
 3   lon            583 non-null    float64
 4   area_m2        700 non-null    float64
 5   price_usd      700 non-null    str
dtypes: float64(3), str(3)
memory usage: 32.9 KB

In [6]:
df1.dtypes

property_type        str
state                str
lat              float64
lon              float64
area_m2          float64
price_usd            str
dtype: object

In [7]:
df1.isnull().sum()

property_type      0
state              0
lat              117
lon              117
area_m2            0
price_usd          0
dtype: int64

In [8]:
df1.dropna()

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
5,house,Yucatán,21.052583,-89.538639,205.0,"$105,191.37"
...,...,...,...,...,...,...
693,house,Puebla,19.051815,-98.277669,198.0,"$115,910.26"
694,apartment,Distrito Federal,19.309208,-99.171906,70.0,"$77,572.89"
696,house,Yucatán,21.050653,-89.558841,334.0,"$137,017.34"
697,house,Yucatán,21.343796,-89.262060,130.0,"$110,404.35"
699,house,Querétaro,20.587378,-100.418361,106.0,"$56,637.97"

In [9]:
df1.isnull().sum()

property_type      0
state              0
lat              117
lon              117
area_m2            0
price_usd          0
dtype: int64

In [10]:
df1

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.0,"$94,835.67"
...,...,...,...,...,...,...
695,house,Morelos,NaN,NaN,310.0,"$237,089.17"
696,house,Yucatán,21.050653,-89.558841,334.0,"$137,017.34"
697,house,Yucatán,21.343796,-89.262060,130.0,"$110,404.35"
698,apartment,Nuevo León,NaN,NaN,155.0,"$184,446.42"
699,house,Querétaro,20.587378,-100.418361,106.0,"$56,637.97"

In [11]:
df1 = df1.dropna()

In [12]:
df1.shape

(583, 6)

In [13]:
df1.isnull().sum()

property_type    0
state            0
lat              0
lon              0
area_m2          0
price_usd        0
dtype: int64

In [14]:
df1.head(10)

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
5,house,Yucatán,21.052583,-89.538639,205.0,"$105,191.37"
6,house,Querétaro,20.716315,-100.452503,320.0,"$274,034.68"
9,house,Morelos,18.812605,-98.954826,281.0,"$151,509.56"
10,house,Chiapas,16.769737,-93.088928,140.0,"$79,029.72"
11,house,Estado de México,19.305407,-99.646948,235.0,"$115,937.75"
12,house,Morelos,18.804197,-98.932816,117.0,"$63,223.78"

In [15]:
df1["price_usd"] = df1['price_usd'].str.replace('$', '', regex=False)
df1["price_usd"] = df1["price_usd"].str.replace(",", "", regex=False)
df1["price_usd"]

0       67965.56
1       63223.78
2       84298.37
3       94308.80
5      105191.37
         ...
693    115910.26
694     77572.89
696    137017.34
697    110404.35
699     56637.97
Name: price_usd, Length: 583, dtype: str

In [16]:
df1["price_usd"] =df1["price_usd"].astype(float)

In [17]:
df1

    property_type             state        lat         lon  area_m2  price_usd
0           house  Estado de México  19.560181  -99.233528    150.0   67965.56
1           house        Nuevo León  25.688436 -100.198807    186.0   63223.78
2       apartment          Guerrero  16.767704  -99.764383     82.0   84298.37
3       apartment          Guerrero  16.829782  -99.911012    150.0   94308.80
5           house           Yucatán  21.052583  -89.538639    205.0  105191.37
..            ...               ...        ...         ...      ...        ...
693         house            Puebla  19.051815  -98.277669    198.0  115910.26
694     apartment  Distrito Federal  19.309208  -99.171906     70.0   77572.89
696         house           Yucatán  21.050653  -89.558841    334.0  137017.34
697         house           Yucatán  21.343796  -89.262060    130.0  110404.35
699         house         Querétaro  20.587378 -100.418361    106.0   56637.97

[583 rows x 6 columns]

In [18]:
df1.dtypes

property_type        str
state                str
lat              float64
lon              float64
area_m2          float64
price_usd        float64
dtype: object

In [19]:
path_2 = "./data/mexico-real-estate-2.csv"
df2 = pd.read_csv(path_2)

In [20]:
df2.isnull().sum()

property_type      0
state              0
lat              129
lon              129
area_m2            0
price_mxn          0
dtype: int64

In [21]:
df2.shape

(700, 6)

In [22]:
df2.head()

  property_type       state        lat         lon  area_m2  price_mxn
0     apartment  Nuevo León  25.721081 -100.345581     72.0  1300000.0
1     apartment      Puebla        NaN         NaN    190.0  2500000.0
2         house     Morelos  23.634501 -102.552788    360.0  5300000.0
3         house     Morelos        NaN         NaN     76.0   820000.0
4         house      Puebla        NaN         NaN    200.0  1100000.0

In [23]:
df2.dtypes

property_type        str
state                str
lat              float64
lon              float64
area_m2          float64
price_mxn        float64
dtype: object

In [24]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  700 non-null    str
 1   state          700 non-null    str
 2   lat            571 non-null    float64
 3   lon            571 non-null    float64
 4   area_m2        700 non-null    float64
 5   price_mxn      700 non-null    float64
dtypes: float64(4), str(2)
memory usage: 32.9 KB

In [25]:
df2 = df2.dropna()

In [26]:
df2.isnull().sum().sum()

np.int64(0)

In [27]:
df2 = df2.assign(
    price_usd = lambda x: x["price_mxn"].div(19)
)
df2

,property_type,state,lat,lon,area_m2,price_mxn,price_usd
0,apartment,Nuevo León,25.721081,-100.345581,72.0,1300000.0,68421.052632
2,house,Morelos,23.634501,-102.552788,360.0,5300000.0,278947.368421
6,apartment,Estado de México,19.272040,-99.572013,85.0,1250000.0,65789.473684
7,house,San Luis Potosí,22.138882,-100.996510,158.0,2120000.0,111578.947368
8,apartment,Distrito Federal,19.394558,-99.129707,65.0,758190.0,39904.736842
...,...,...,...,...,...,...,...
695,house,Morelos,18.917542,-98.963181,140.0,1450000.0,76315.789474
696,house,Distrito Federal,19.472128,-99.146697,190.0,1943000.0,102263.157895
697,house,Estado de México,19.234984,-99.558175,115.0,2100000.0,110526.315789
698,house,Puebla,18.918714,-98.426639,90.0,890000.0,46842.105263
699,house,Yucatán,21.075163,-89.516731,185.0,1695000.0,89210.526316

In [28]:
df2 = df2.drop(columns=["price_mxn"])
df2

,property_type,state,lat,lon,area_m2,price_usd
0,apartment,Nuevo León,25.721081,-100.345581,72.0,68421.052632
2,house,Morelos,23.634501,-102.552788,360.0,278947.368421
6,apartment,Estado de México,19.272040,-99.572013,85.0,65789.473684
7,house,San Luis Potosí,22.138882,-100.996510,158.0,111578.947368
8,apartment,Distrito Federal,19.394558,-99.129707,65.0,39904.736842
...,...,...,...,...,...,...
695,house,Morelos,18.917542,-98.963181,140.0,76315.789474
696,house,Distrito Federal,19.472128,-99.146697,190.0,102263.157895
697,house,Estado de México,19.234984,-99.558175,115.0,110526.315789
698,house,Puebla,18.918714,-98.426639,90.0,46842.105263
699,house,Yucatán,21.075163,-89.516731,185.0,89210.526316

In [29]:
df2.columns.tolist()

['property_type', 'state', 'lat', 'lon', 'area_m2', 'price_usd']

In [30]:
df1.columns.tolist()

['property_type', 'state', 'lat', 'lon', 'area_m2', 'price_usd']

In [31]:
path_3 = "./data/mexico-real-estate-3.csv"
df3 = (
    pd.read_csv(path_3)
    .dropna()
)
df3

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.0,48550.59
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.0,168636.73
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.0,86932.69
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.0,68508.67
5,house,|México|Jalisco|Guadalajara|,"20.689157,-103.366728",175.0,102763.00
...,...,...,...,...,...
695,house,|México|Jalisco|Tlajomulco de Zúñiga|Tlajomulc...,"20.532264,-103.484418",175.0,121178.91
696,house,|México|Morelos|Jiutepec|,"18.9289862,-99.1802147",100.0,47417.83
697,house,|México|Yucatán|Mérida|,"21.0284038368,-89.6530058049",81.0,39524.23
698,house,|México|San Luis Potosí|San Luis Potosí|,"22.11830417,-101.0321938992",360.0,245050.24
699,house,|México|Estado de México|Toluca|Metepec|,"19.233201,-99.558519",115.0,110667.85

In [32]:
df3.dtypes

property_type                  str
place_with_parent_names        str
lat-lon                        str
area_m2                    float64
price_usd                  float64
dtype: object

In [33]:
df3 = df3.assign(
    lat = lambda x : x["lat-lon"].str.split(",", expand=True)[0].astype(float),
    lon = lambda x : x["lat-lon"].str.split(",", expand=True)[1].astype(float),
    state = lambda x : x["place_with_parent_names"].str.split("|", expand=True)[2]
)
df3

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd,lat,lon,state
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.0,48550.59,19.525890,-99.151703,Distrito Federal
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.0,168636.73,19.264054,-99.572753,Estado de México
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.0,86932.69,19.268629,-99.671722,Estado de México
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.0,68508.67,19.511938,-96.871956,Veracruz de Ignacio de la Llave
5,house,|México|Jalisco|Guadalajara|,"20.689157,-103.366728",175.0,102763.00,20.689157,-103.366728,Jalisco
...,...,...,...,...,...,...,...,...
695,house,|México|Jalisco|Tlajomulco de Zúñiga|Tlajomulc...,"20.532264,-103.484418",175.0,121178.91,20.532264,-103.484418,Jalisco
696,house,|México|Morelos|Jiutepec|,"18.9289862,-99.1802147",100.0,47417.83,18.928986,-99.180215,Morelos
697,house,|México|Yucatán|Mérida|,"21.0284038368,-89.6530058049",81.0,39524.23,21.028404,-89.653006,Yucatán
698,house,|México|San Luis Potosí|San Luis Potosí|,"22.11830417,-101.0321938992",360.0,245050.24,22.118304,-101.032194,San Luis Potosí
699,house,|México|Estado de México|Toluca|Metepec|,"19.233201,-99.558519",115.0,110667.85,19.233201,-99.558519,Estado de México

In [34]:
df3.dtypes

property_type                  str
place_with_parent_names        str
lat-lon                        str
area_m2                    float64
price_usd                  float64
lat                        float64
lon                        float64
state                          str
dtype: object

In [35]:
df3 = df3.drop(columns=["place_with_parent_names","lat-lon"])
df3

,property_type,area_m2,price_usd,lat,lon,state
0,apartment,71.0,48550.59,19.525890,-99.151703,Distrito Federal
1,house,233.0,168636.73,19.264054,-99.572753,Estado de México
2,house,300.0,86932.69,19.268629,-99.671722,Estado de México
4,apartment,84.0,68508.67,19.511938,-96.871956,Veracruz de Ignacio de la Llave
5,house,175.0,102763.00,20.689157,-103.366728,Jalisco
...,...,...,...,...,...,...
695,house,175.0,121178.91,20.532264,-103.484418,Jalisco
696,house,100.0,47417.83,18.928986,-99.180215,Morelos
697,house,81.0,39524.23,21.028404,-89.653006,Yucatán
698,house,360.0,245050.24,22.118304,-101.032194,San Luis Potosí
699,house,115.0,110667.85,19.233201,-99.558519,Estado de México

In [36]:
df3.shape

(582, 6)

In [37]:
# Check if all column sets are identical
columns_match = set(df1.columns) == set(df2.columns) == set(df3.columns)

if columns_match:
    print("✅ All DataFrames have the same columns.")
else:
    print("❌ Column mismatch detected!")
    # Optional: See the difference
    print("df1 vs df2 diff:", set(df1.columns) ^ set(df2.columns))
    print("df2 vs df3 diff:", set(df2.columns) ^ set(df3.columns))

✅ All DataFrames have the same columns.

In [38]:
df = pd.concat([df1,df2,df3], ignore_index=True)
print(f"Combined shape: {df.shape}")
df.head()

Combined shape: (1736, 6)

  property_type             state        lat         lon  area_m2  price_usd
0         house  Estado de México  19.560181  -99.233528    150.0   67965.56
1         house        Nuevo León  25.688436 -100.198807    186.0   63223.78
2     apartment          Guerrero  16.767704  -99.764383     82.0   84298.37
3     apartment          Guerrero  16.829782  -99.911012    150.0   94308.80
4         house           Yucatán  21.052583  -89.538639    205.0  105191.37

In [39]:
if df.shape[0] == ((df1.shape[0]) + (df2.shape[0]) + (df3.shape[0])):
    print("✅ All DataFrames have the same columns.")
else:
    print("❌ All DataFrames dont have the same columns.")

✅ All DataFrames have the same columns.

In [40]:
df.shape[1]

6

In [41]:
df.to_csv("./data/cleaned-and-tidy-data.csv", index=False)

In [42]:
df.describe()

               lat          lon      area_m2      price_usd
count  1736.000000  1736.000000  1736.000000    1736.000000
mean     20.765410   -98.798575   170.261521  115331.980800
std       2.743425     4.882553    80.594539   65426.173793
min      15.752900  -117.054763    60.000000   33157.894737
25%      19.275200  -100.392553   101.750000   65789.473684
50%      19.620518   -99.204001   156.000000   99262.132105
75%      21.073428   -98.245911   220.000000  150846.665000
max      32.665619   -86.767539   385.000000  326733.660000

In [43]:
summary = df.describe()